# Generated by Django 5.1.3 on 2025-12-08 09:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('script_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='编排任务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已激活'), ('disabled', '已禁用')], default='draft', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '编排任务',
                'verbose_name_plural': '编排任务管理',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='OrchestrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('running', '执行中'), ('completed', '已完成'), ('failed', '执行失败'), ('stopped', '手动停止')], default='running', max_length=20, verbose_name='执行状态')),
                ('total_steps', models.PositiveIntegerField(verbose_name='总步骤数')),
                ('completed_steps', models.PositiveIntegerField(default=0, verbose_name='已完成步骤数')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('orchestration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task_orchestration.orchestrationtask', verbose_name='关联编排任务')),
            ],
            options={
                'verbose_name': '编排执行日志',
                'verbose_name_plural': '编排执行日志管理',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_order', models.PositiveIntegerField(verbose_name='执行顺序')),
                ('run_duration', models.PositiveIntegerField(help_text='指定该子任务运行多久后自动停止', verbose_name='运行时长(秒)')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('orchestration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='task_orchestration.orchestrationtask', verbose_name='所属编排任务')),
                ('script_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_center.scripttask', verbose_name='关联脚本任务')),
            ],
            options={
                'verbose_name': '子任务步骤',
                'verbose_name_plural': '子任务步骤管理',
                'ordering': ['execution_order'],
                'unique_together': {('orchestration', 'execution_order')},
            },
        ),
        migrations.CreateModel(
            name='StepExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('stopped', '已停止'), ('failed', '执行失败')], default='pending', max_length=20, verbose_name='执行状态')),
                ('script_log_id', models.IntegerField(blank=True, help_text='关联script_center的TaskExecutionLog', null=True, verbose_name='脚本任务日志ID')),
                ('orchestration_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='task_orchestration.orchestrationlog', verbose_name='所属编排日志')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_orchestration.taskstep', verbose_name='关联步骤')),
            ],
            options={
                'verbose_name': '步骤执行日志',
                'verbose_name_plural': '步骤执行日志管理',
                'ordering': ['start_time'],
            },
        ),
    ]
