# Generated by Django 5.1.3 on 2025-12-08 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adb_manager', '0003_alter_adbdevice_device_ip_and_more'),
        ('task_orchestration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationlog',
            name='device',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='adb_manager.adbdevice', verbose_name='执行设备'),
            preserve_default=False,
        ),
    ]
