# Generated by Django 5.1.3 on 2025-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_orchestration', '0002_orchestrationlog_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepexecutionlog',
            name='error_msg',
            field=models.TextField(blank=True, null=True, verbose_name='步骤错误信息'),
        ),
        migrations.AlterField(
            model_name='orchestrationlog',
            name='status',
            field=models.CharField(choices=[('running', '执行中'), ('completed', '已完成'), ('part_failed', '部分失败'), ('failed', '执行失败'), ('stopped', '手动停止')], default='running', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='stepexecutionlog',
            name='status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('timeout', '执行超时'), ('failed', '执行失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
    ]
