# Generated by Django 5.1.3 on 2025-12-08 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adb_manager', '0003_alter_adbdevice_device_ip_and_more'),
        ('task_orchestration', '0003_stepexecutionlog_error_msg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stepexecutionlog',
            options={'ordering': ['step__execution_order'], 'verbose_name': '步骤执行日志', 'verbose_name_plural': '步骤执行日志管理'},
        ),
        migrations.RenameField(
            model_name='orchestrationlog',
            old_name='status',
            new_name='exec_status',
        ),
        migrations.RemoveField(
            model_name='stepexecutionlog',
            name='script_log_id',
        ),
        migrations.RemoveField(
            model_name='stepexecutionlog',
            name='status',
        ),
        migrations.AddField(
            model_name='orchestrationlog',
            name='exec_command',
            field=models.TextField(blank=True, null=True, verbose_name='执行命令'),
        ),
        migrations.AddField(
            model_name='orchestrationlog',
            name='exec_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='执行耗时(秒)'),
        ),
        migrations.AddField(
            model_name='orchestrationlog',
            name='stderr',
            field=models.TextField(blank=True, null=True, verbose_name='错误输出'),
        ),
        migrations.AddField(
            model_name='orchestrationlog',
            name='stdout',
            field=models.TextField(blank=True, null=True, verbose_name='标准输出'),
        ),
        migrations.AddField(
            model_name='stepexecutionlog',
            name='exec_command',
            field=models.TextField(blank=True, null=True, verbose_name='执行命令'),
        ),
        migrations.AddField(
            model_name='stepexecutionlog',
            name='exec_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='执行耗时(秒)'),
        ),
        migrations.AddField(
            model_name='stepexecutionlog',
            name='exec_status',
            field=models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('timeout', '执行超时'), ('failed', '执行失败'), ('stopped', '已停止'), ('error', '系统错误')], default='pending', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AddField(
            model_name='stepexecutionlog',
            name='return_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='返回码'),
        ),
        migrations.AddField(
            model_name='stepexecutionlog',
            name='stderr',
            field=models.TextField(blank=True, null=True, verbose_name='错误输出'),
        ),
        migrations.AddField(
            model_name='stepexecutionlog',
            name='stdout',
            field=models.TextField(blank=True, null=True, verbose_name='标准输出'),
        ),
        migrations.AlterField(
            model_name='orchestrationlog',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adb_manager.adbdevice', verbose_name='执行设备'),
        ),
    ]
