# Generated by Django 5.1.3 on 2025-12-28 19:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_orchestration', '0004_alter_stepexecutionlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationManagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_task_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='原任务名称')),
                ('operation_type', models.CharField(choices=[('create', '新增'), ('edit', '编辑'), ('delete', '删除'), ('clone', '克隆')], max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('details', models.TextField(blank=True, null=True, verbose_name='操作详情')),
                ('orchestration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_logs', to='task_orchestration.orchestrationtask', verbose_name='关联编排任务')),
            ],
            options={
                'verbose_name': '编排任务管理日志',
                'verbose_name_plural': '编排任务管理日志',
                'ordering': ['-operation_time'],
            },
        ),
    ]
