# Generated by Django 5.1.3 on 2025-12-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_orchestration', '0005_orchestrationmanagementlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationmanagementlog',
            name='original_task_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='原任务ID'),
        ),
    ]
