# Generated by Django 5.1.3 on 2025-12-11 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adb_manager', '0003_alter_adbdevice_device_ip_and_more'),
        ('task_orchestration', '0004_alter_stepexecutionlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='定时任务名称')),
                ('cron_expression', models.CharField(default='0 0 * * *', help_text='格式：分 时 日 月 周，支持标准Cron语法。示例：<br/>0 8 * * * → 每天8点执行<br/>0 0 * * 1,3,5 → 每周一/三/五0点执行<br/>0 12 1,15 * * → 每月1/15号12点执行<br/>*/30 * * * * → 每30分钟执行一次', max_length=100, verbose_name='Cron表达式')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最后执行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(blank=True, help_text='为空则自动选择在线设备', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adb_manager.adbdevice', verbose_name='指定执行设备')),
                ('orchestration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='task_orchestration.orchestrationtask', verbose_name='关联编排任务')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务管理',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_status', models.CharField(choices=[('success', '执行成功'), ('failed', '执行失败'), ('running', '执行中')], default='running', max_length=20, verbose_name='执行状态')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adb_manager.adbdevice', verbose_name='执行设备')),
                ('orchestration_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_orchestration.orchestrationlog', verbose_name='关联编排日志')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='task_scheduler.scheduletask', verbose_name='关联定时任务')),
            ],
            options={
                'verbose_name': '定时任务执行日志',
                'verbose_name_plural': '定时任务执行日志管理',
                'ordering': ['-start_time'],
            },
        ),
    ]
