# Generated by Django 5.1.3 on 2025-12-28 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexecutionlog',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
