# Generated by Django 5.1.3 on 2025-12-28 20:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_scheduler', '0002_alter_scheduleexecutionlog_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleManagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', '新增'), ('edit', '编辑'), ('delete', '删除'), ('toggle', '启用/禁用')], max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(help_text='执行操作的用户名', max_length=100, verbose_name='操作人')),
                ('operation_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间')),
                ('details', models.TextField(blank=True, help_text='记录操作前后的变化', null=True, verbose_name='操作详情')),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='task_scheduler.scheduletask', verbose_name='关联定时任务')),
            ],
            options={
                'verbose_name': '定时任务管理日志',
                'verbose_name_plural': '定时任务管理日志',
                'ordering': ['-operation_time'],
            },
        ),
    ]
