# Generated by Django 5.1.3 on 2025-12-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADBDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device_name', models.CharField(help_text='如：游戏手机1', max_length=50, verbose_name='设备名称')),
                ('device_ip', models.GenericIPAddressField(help_text='局域网IP，如192.168.3.100', verbose_name='设备IP')),
                ('device_port', models.IntegerField(default=5555, help_text='默认5555', verbose_name='ADB端口')),
                ('device_serial', models.CharField(blank=True, help_text='ADB设备号，如192.168.3.100:5555或USB串号', max_length=100, null=True, verbose_name='设备序列号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用监控')),
            ],
            options={
                'verbose_name': 'ADB设备',
                'verbose_name_plural': 'ADB设备管理',
            },
        ),
    ]
