# Generated by Django 5.1.3 on 2025-12-05 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adb_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adbdevice',
            name='user',
            field=models.ForeignKey(blank=True, help_text='绑定该设备的用户（为空则所有用户可操作）', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterUniqueTogether(
            name='adbdevice',
            unique_together={('device_ip', 'device_port')},
        ),
    ]
