# Generated by Django 5.1.3 on 2025-12-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adb_manager', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adbdevice',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, help_text='局域网IP（序列号连接时可不填），如192.168.3.100', null=True, verbose_name='设备IP'),
        ),
        migrations.AlterField(
            model_name='adbdevice',
            name='device_port',
            field=models.IntegerField(blank=True, default=5555, help_text='默认5555（序列号连接时可不填）', null=True, verbose_name='ADB端口'),
        ),
        migrations.AlterField(
            model_name='adbdevice',
            name='device_serial',
            field=models.CharField(blank=True, help_text='ADB设备序列号（优先使用），如10AF5E1AKU003NR或192.168.3.100:5555', max_length=100, null=True, verbose_name='设备序列号'),
        ),
    ]
