# Generated by Django 5.1.3 on 2025-12-28 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adb_manager', '0003_alter_adbdevice_device_ip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ADBDeviceOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operation_type', models.CharField(choices=[('connect', '连接设备'), ('disconnect', '断开设备'), ('add', '添加设备'), ('edit', '编辑设备'), ('delete', '删除设备'), ('enable_wireless', '开启无线ADB'), ('connect_all', '一键连接所有'), ('disconnect_all', '一键断开所有'), ('refresh_all', '刷新所有状态')], max_length=20, verbose_name='操作类型')),
                ('operation_result', models.BooleanField(default=True, verbose_name='操作结果')),
                ('operation_details', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adb_manager.adbdevice', verbose_name='操作设备')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '设备操作日志',
                'verbose_name_plural': '设备操作日志管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
