# Generated by Django 5.1.3 on 2026-04-16 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adb_manager', '0004_adbdeviceoperationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adbdevice',
            index=models.Index(fields=['is_active'], name='adb_manager_is_acti_05b01c_idx'),
        ),
        migrations.AddIndex(
            model_name='adbdevice',
            index=models.Index(fields=['device_serial'], name='adb_manager_device__6c604b_idx'),
        ),
        migrations.AddIndex(
            model_name='adbdevice',
            index=models.Index(fields=['user'], name='adb_manager_user_id_00b289_idx'),
        ),
    ]
