"""
Django settings for EasyADB project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import logging
logger = logging.getLogger(__name__)
# 加载.env文件（项目根目录，与manage.py同级）
# 先定位.env文件路径，确保加载成功
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = BASE_DIR / ".env"
load_dotenv(dotenv_path=env_path)  # 显式指定.env路径，避免加载失败


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# 转换为布尔值（.env中是字符串，需手动转换）
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# 处理ALLOWED_HOSTS（逗号分隔转列表）
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
# 过滤空值（避免配置为空时出现''）
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    "adb_manager.apps.AdbManagerConfig",
    "script_center.apps.ScriptCenterConfig",
    "user_auth.apps.UserAuthConfig",
    "task_scheduler.apps.TaskSchedulerConfig",
    "frontend.apps.FrontendConfig",
    "common.apps.CommonConfig",
    "task_orchestration.apps.TaskOrchestrationConfig"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EasyADB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 【新增】添加这一行
                'script_center.context_processors.global_settings',
            ],
        },
    },
]


WSGI_APPLICATION = 'EasyADB.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 从.env读取数据库文件名，结合BASE_DIR拼接路径
        'NAME': BASE_DIR / os.getenv("DB_FILENAME"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/
LANGUAGE_CODE = os.getenv("LANGUAGE_CODE")
TIME_ZONE = os.getenv("TIME_ZONE")
USE_I18N = True
USE_TZ = os.getenv("USE_TZ", "False").lower() == "true"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Redis配置（从.env读取）
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT"))  # 转换为整数
REDIS_DB = int(os.getenv("REDIS_DB"))      # 转换为整数

# Celery核心配置（强制Celery读取Django的配置）
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
CELERY_TIMEZONE = TIME_ZONE  # 和Django时区绑定
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # 启动时重试连接
CELERY_TASK_SERIALIZER = os.getenv("CELERY_TASK_SERIALIZER")
CELERY_RESULT_SERIALIZER = os.getenv("CELERY_RESULT_SERIALIZER")
CELERY_ACCEPT_CONTENT = [os.getenv("CELERY_TASK_SERIALIZER")]
CELERY_RESULT_EXPIRES = int(os.getenv("CELERY_RESULT_EXPIRES"))

# 自定义用户模型
AUTH_USER_MODEL = 'user_auth.CustomUser'

# CORS配置（开发环境）
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS").lower() == "true"

# ASGI配置（Channels）
ASGI_APPLICATION = 'EasyADB.asgi.application'

# WebSocket通道层配置（使用Redis）
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],  # 使用从.env读取的Redis配置
        },
    },
}

# 内置脚本目录配置（指向 builtin_scripts/examples）
BUILTIN_SCRIPTS_DIR = os.path.join(BASE_DIR, 'builtin_scripts', 'examples')

BUILTIN_SCRIPTS_ROOT = os.path.join(BASE_DIR, 'builtin_scripts')

SHOW_BUILTIN_SCRIPTS = os.getenv("SHOW_BUILTIN_SCRIPTS", "False").lower() == "true"

USE_CELERY = os.getenv("USE_CELERY", "True").lower() == "true"
try:
    # 尝试检测 Celery 是否可用
    from celery import Celery
    # 尝试初始化 Celery（仅检测，不重复配置）
    app = Celery("EasyADB")  # 替换为你的项目名
    app.config_from_object('django.conf:settings', namespace='CELERY')
    # 尝试连接 Broker（可选，更严格的检测）
    # app.connection().connect()
    logger.info("Celery 初始化成功，启用异步任务模式")
except Exception as e:
    logger.warning(f"Celery 不可用，将使用后台线程模式：{str(e)}")

# ====================== 新增：Script Center 优化配置 ======================
SCRIPT_PYTHON_WARNING_KEYWORD = os.getenv("SCRIPT_PYTHON_WARNING_KEYWORD", "WindowsApps")
# Python版本（用于构建动态fallback路径）
PYTHON_VERSION = os.getenv("PYTHON_VERSION", "311")

# Python Fallback路径（解决WindowsApps问题）
# 1. 从.env读取分号分隔的固定路径
PYTHON_FALLBACK_PATHS = os.getenv("PYTHON_FALLBACK_PATHS", "").split(";")
# 2. 过滤空值并去重
PYTHON_FALLBACK_PATHS = list({path.strip() for path in PYTHON_FALLBACK_PATHS if path.strip()})
# 3. 添加动态用户目录路径（自动适配当前用户）
dynamic_python_path = os.path.expanduser(
    f"~\\AppData\\Local\\Programs\\Python\\Python{PYTHON_VERSION}\\python.exe"
)
if dynamic_python_path not in PYTHON_FALLBACK_PATHS:
    PYTHON_FALLBACK_PATHS.append(dynamic_python_path)

# Redis连接池配置（复用已有REDIS_HOST/REDIS_PORT/REDIS_DB）
REDIS_SOCKET_TIMEOUT = int(os.getenv("REDIS_SOCKET_TIMEOUT", 2))

# 脚本执行超时配置
SCRIPT_EXECUTION_TIMEOUT = int(os.getenv("SCRIPT_EXECUTION_TIMEOUT", 3000))  # 50分钟

# 进程终止相关配置（复用部分已有配置）
SCRIPT_GRACEFUL_TERMINATE_WAIT = int(os.getenv("SCRIPT_GRACEFUL_TERMINATE_WAIT", 5))  # 优雅等待默认时间
# （复用已有SCRIPT_STOP_WAIT_TIME、SCRIPT_PROCESS_TERMINATE_WAIT、SCRIPT_REDIS_STOP_FLAG_EXPIRE）

# Redis键名配置
SCRIPT_REDIS_PROCESS_HASH = os.getenv("SCRIPT_REDIS_PROCESS_HASH", "script_running_processes")
SCRIPT_REDIS_STOP_FLAG_PREFIX = os.getenv("SCRIPT_REDIS_STOP_FLAG_PREFIX", "airtest_stop_flag_")

# ====================== Task Orchestration 编排任务配置 ======================
# 日志与展示配置
ORCH_LOG_FILE = os.getenv("ORCH_LOG_FILE", "orchestration_execution.log")
ORCH_RECENT_LOGS_LIMIT = int(os.getenv("ORCH_RECENT_LOGS_LIMIT", 10))

# 执行超时与进程控制
ORCH_STEP_TIMEOUT_BUFFER = int(os.getenv("ORCH_STEP_TIMEOUT_BUFFER", 10))
ORCH_PROCESS_TERMINATE_WAIT = int(os.getenv("ORCH_PROCESS_TERMINATE_WAIT", 1))
ORCH_CELERY_TERMINATE_FORCE = os.getenv("ORCH_CELERY_TERMINATE_FORCE", "True").lower() == "true"
ORCH_CELERY_TASK_TIME_LIMIT = int(os.getenv("ORCH_CELERY_TASK_TIME_LIMIT", 3600))

# Redis键名配置
ORCH_REDIS_PROCESS_HASH = os.getenv("ORCH_REDIS_PROCESS_HASH", "orch_running_processes")

# 执行环境变量配置
ORCH_PYTHONIOENCODING = os.getenv("ORCH_PYTHONIOENCODING", "utf-8")
ORCH_PYTHONLEGACYWINDOWSSTDIO = os.getenv("ORCH_PYTHONLEGACYWINDOWSSTDIO", "utf-8")
ORCH_LC_ALL = os.getenv("ORCH_LC_ALL", "en_US.UTF-8")
ORCH_LANG = os.getenv("ORCH_LANG", "en_US.UTF-8")

# 其他配置
ORCH_MOBILE_VALID_LENGTH = int(os.getenv("ORCH_MOBILE_VALID_LENGTH", 11))
