# Generated by Django 5.1.3 on 2025-12-06 04:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adb_manager', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='如：自动化测试任务1', max_length=100, unique=True, verbose_name='任务名称')),
                ('task_desc', models.TextField(blank=True, help_text='任务详细说明', null=True, verbose_name='任务描述')),
                ('python_path', models.CharField(default='C:\\Users\\TanZhenJie\\AppData\\Local\\Microsoft\\WindowsApps\\python3.11.exe', help_text='Python.exe的完整路径', max_length=500, verbose_name='Python解释器路径')),
                ('script_path', models.CharField(help_text='如：C:\\test\\test4.py（指向.py文件）', max_length=500, verbose_name='脚本文件路径')),
                ('airtest_mode', models.BooleanField(default=False, help_text='勾选则用airtest run方式执行', verbose_name='是否使用Airtest模式')),
                ('log_path', models.CharField(blank=True, default='./logs', help_text='脚本执行日志保存路径', max_length=500, null=True, verbose_name='日志保存路径')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已激活'), ('disabled', '已禁用')], default='active', max_length=20, verbose_name='任务状态')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '脚本任务',
                'verbose_name_plural': '脚本任务管理',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_status', models.CharField(choices=[('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('timeout', '执行超时'), ('error', '执行异常')], default='running', max_length=20, verbose_name='执行状态')),
                ('exec_command', models.TextField(blank=True, null=True, verbose_name='执行命令')),
                ('stdout', models.TextField(blank=True, null=True, verbose_name='标准输出')),
                ('stderr', models.TextField(blank=True, null=True, verbose_name='错误输出')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('exec_duration', models.FloatField(blank=True, null=True, verbose_name='执行耗时(秒)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adb_manager.adbdevice', verbose_name='执行设备')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='script_center.scripttask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '执行日志',
                'verbose_name_plural': '执行日志管理',
                'ordering': ['-start_time'],
            },
        ),
    ]
