# Generated by Django 5.1.3 on 2025-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripttask',
            name='is_long_running',
            field=models.BooleanField(default=False, help_text='勾选后任务无超时限制，仅响应手动停止信号', verbose_name='是否长期运行'),
        ),
        migrations.AddField(
            model_name='scripttask',
            name='timeout_seconds',
            field=models.IntegerField(default=300, help_text='普通任务超时时间，0=不限制，默认5分钟', verbose_name='超时时间(秒)'),
        ),
    ]
