# Generated by Django 5.1.3 on 2025-12-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_center', '0002_scripttask_is_long_running_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutionlog',
            name='return_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='返回码'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='exec_status',
            field=models.CharField(choices=[('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('timeout', '执行超时'), ('error', '执行异常'), ('stopped', '已停止')], default='running', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='stderr',
            field=models.TextField(blank=True, default='', verbose_name='错误输出'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='stdout',
            field=models.TextField(blank=True, default='', verbose_name='标准输出'),
        ),
    ]
