# Generated by Django 5.1.3 on 2025-12-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_center', '0003_taskexecutionlog_return_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskexecutionlog',
            name='return_code',
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='exec_status',
            field=models.CharField(choices=[('running', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('timeout', '执行超时'), ('error', '执行异常')], default='running', max_length=20, verbose_name='执行状态'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='stderr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='错误输出'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='stdout',
            field=models.TextField(blank=True, null=True, verbose_name='标准输出'),
        ),
    ]
