# Generated by Django 5.1.3 on 2025-12-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_center', '0004_remove_taskexecutionlog_return_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scripttask',
            name='is_long_running',
        ),
        migrations.RemoveField(
            model_name='scripttask',
            name='timeout_seconds',
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='stderr',
            field=models.TextField(blank=True, null=True, verbose_name='错误输出'),
        ),
    ]
