# Generated by Django 5.1.3 on 2025-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_center', '0005_remove_scripttask_is_long_running_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='exec_command',
            field=models.TextField(blank=True, default='', verbose_name='执行命令'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='stderr',
            field=models.TextField(blank=True, default='', verbose_name='错误输出'),
        ),
        migrations.AlterField(
            model_name='taskexecutionlog',
            name='stdout',
            field=models.TextField(blank=True, default='', verbose_name='标准输出'),
        ),
    ]
