# Generated by Django 5.1.3 on 2026-04-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_center', '0007_scripttaskmanagementlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripttask',
            name='python_path',
            field=models.CharField(blank=True, help_text='不填写则自动使用Django当前运行的Python解释器', max_length=500, null=True, verbose_name='Python解释器路径'),
        ),
        migrations.AlterField(
            model_name='scripttaskmanagementlog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='操作详情'),
        ),
        migrations.AlterField(
            model_name='scripttaskmanagementlog',
            name='operator',
            field=models.CharField(max_length=100, verbose_name='操作人'),
        ),
    ]
