# Generated by Django 5.1.3 on 2026-04-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adb_manager', '0004_adbdeviceoperationlog'),
        ('script_center', '0008_alter_scripttask_python_path_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scripttask',
            index=models.Index(fields=['task_name'], name='script_cent_task_na_2a2379_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttask',
            index=models.Index(fields=['status'], name='script_cent_status_9d1490_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttaskmanagementlog',
            index=models.Index(fields=['task'], name='script_cent_task_id_42627e_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttaskmanagementlog',
            index=models.Index(fields=['operation'], name='script_cent_operati_a8645e_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttaskmanagementlog',
            index=models.Index(fields=['operator'], name='script_cent_operato_a6c4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='scripttaskmanagementlog',
            index=models.Index(fields=['-operation_time'], name='script_cent_operati_cc48bc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['task'], name='script_cent_task_id_4ce18c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['device'], name='script_cent_device__270109_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['exec_status'], name='script_cent_exec_st_eb079a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskexecutionlog',
            index=models.Index(fields=['-start_time'], name='script_cent_start_t_bf0f41_idx'),
        ),
    ]
