# Generated by Django 5.1.3 on 2026-04-16 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_center', '0009_scripttask_script_cent_task_na_2a2379_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuiltinScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='脚本名称')),
                ('identifier', models.SlugField(max_length=100, unique=True, verbose_name='唯一标识')),
                ('category', models.CharField(choices=[('DEVICE', '设备控制'), ('AD', '广告自动化'), ('MONKEY', '压力测试'), ('UTIL', '实用工具')], db_index=True, max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='功能介绍')),
                ('file_path', models.CharField(help_text='相对于 BUILTIN_SCRIPTS_ROOT', max_length=255, verbose_name='文件相对路径')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '内置脚本',
                'verbose_name_plural': '内置脚本库',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScriptParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='参数名 (如: --count)')),
                ('param_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('float', '小数'), ('boolean', '开关')], default='string', max_length=10, verbose_name='类型')),
                ('label', models.CharField(max_length=100, verbose_name='显示名称')),
                ('default_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认值')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='帮助说明')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='script_center.builtinscript')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
